FailSafeContext/DeviceControlServer: gcc 11.2 compatibility: avoid aggregate initialisation of anonymous union substructs
- This is a regression in gcc 11.2, fixed only in gcc 12,
  see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102740

- it causes error messages like:
  `FailSafeContext.cpp:91:114: error: 'chip::DeviceLayer::ChipDeviceEvent::<unnamed union>' has no non-static data member named 'fabricIndex'`

- gcc 11.2 is in use in not-yet-obsolete toolchains like OpenWrt 22.03,
  and these two files seem to be the only place in matter SDK using this
  kind of initialisation.